import {z} from 'zod';
import {GrcEvidence} from './grc.ts';
const Id=z.uuid(),Time=z.iso.datetime(),Text=z.string().trim().min(1).max(500);
const recorded={id:Id,recorded_by:Id,recorded_at:Time};
export const GrcAuditCreate=z.strictObject({title:Text,objective:Text,owner_reference:Text,due_at:Time,control_ids:z.array(Id).min(1).max(100)}).superRefine((v,c)=>{if(new Set(v.control_ids).size!==v.control_ids.length)c.addIssue({code:'custom',path:['control_ids'],message:'Duplicate control.'});});
export const GrcAudit=GrcAuditCreate.safeExtend(recorded);
export const GrcAuditRequestCreate=z.strictObject({control_id:Id,description:Text,assignee_reference:Text,due_at:Time});
export const GrcAuditRequest=GrcAuditRequestCreate.extend({...recorded,audit_id:Id});
export const GrcAuditResponseCreate=z.strictObject({evidence_id:Id,explanation:Text});
export const GrcAuditResponse=GrcAuditResponseCreate.extend({...recorded,request_id:Id,evidence_snapshot:GrcEvidence});
export const GrcAuditResponseReviewCreate=z.strictObject({response_id:Id,decision:z.enum(['ACCEPT','REJECT']),reason:Text});
export const GrcAuditResponseReview=GrcAuditResponseReviewCreate.extend({...recorded,request_id:Id});
export const GrcAuditResponseHistoryRecord=GrcAuditResponse.extend({review:GrcAuditResponseReview.nullable()});
export const GrcAuditCloseCreate=z.strictObject({reason:Text});
export const GrcAuditClosure=GrcAuditCloseCreate.extend({...recorded,audit_id:Id,accepted_response_ids:z.array(Id).min(1).max(100),certification_asserted:z.literal(false)});
export const GrcAuditDetail=z.strictObject({audit:GrcAudit,closure:GrcAuditClosure.nullable()});
export const GrcAuditRequestDetail=z.strictObject({request:GrcAuditRequest,response:GrcAuditResponse.nullable(),review:GrcAuditResponseReview.nullable(),state:z.enum(['OPEN','REVIEW_PENDING','REJECTED','ACCEPTED','STALE']),as_of:Time});
const page=<T extends z.ZodType>(schema:T)=>z.strictObject({items:z.array(schema).max(100),next_cursor:z.string().max(200).nullable()});
export const grcAuditSchemas={GrcAuditCreate,GrcAudit,GrcAuditDetail,GrcAuditList:page(GrcAudit),GrcAuditRequestCreate,GrcAuditRequest,GrcAuditRequestList:page(GrcAuditRequest),GrcAuditResponseCreate,GrcAuditResponse,GrcAuditResponseReviewCreate,GrcAuditResponseReview,GrcAuditCloseCreate,GrcAuditClosure,GrcAuditRequestDetail,GrcAuditResponseHistoryRecord,GrcAuditResponseHistoryList:page(GrcAuditResponseHistoryRecord)};
