import { randomUUID } from 'node:crypto';
import { authenticatorCode } from '../../packages/testing/src/http-fixture.ts';
import { test, expect, loginUi } from './fixture.ts';

test('B01 configure purpose/notice/system/policy and distinct reviewer publication persists',async({page,browser,h})=>{
  await loginUi(page,h,'admin');await page.goto('/workspace/configuration');const suffix=randomUUID().slice(0,8);
  let form=page.locator('form').filter({has:page.getByRole('heading',{name:'Create purpose',exact:true})});
  await form.getByLabel('Purpose name').fill('Browser purpose '+suffix);await form.getByLabel('Purpose condition').selectOption('promotional_marketing');await form.getByLabel('Description').fill('Synthetic browser acceptance purpose');
  let response=page.waitForResponse(r=>r.url().endsWith('/admin/purposes')&&r.request().method()==='POST');await form.getByRole('button',{name:'Create purpose',exact:true}).click();let received=await response;expect(received.status()).toBe(201);const purpose=await received.json();
  await page.getByRole('button',{name:'Systems',exact:true}).click();form=page.locator('form').filter({has:page.getByRole('heading',{name:'Create synthetic system',exact:true})});await form.getByLabel('System name').fill('Browser CRM '+suffix);await form.getByLabel('Connector').selectOption('SYNTHETIC_CRM');
  response=page.waitForResponse(r=>r.url().endsWith('/admin/systems')&&r.request().method()==='POST');await form.getByRole('button',{name:'Create synthetic system',exact:true}).click();received=await response;expect(received.status()).toBe(201);const system=await received.json();
  await page.getByRole('button',{name:'Notices',exact:true}).click();form=page.locator('form').filter({has:page.getByRole('heading',{name:'Create notice',exact:true})});await form.getByLabel('Notice purpose').selectOption(purpose.id);await form.getByLabel('Notice title').fill('Browser notice '+suffix);await form.getByLabel('Notice content').fill('Optional synthetic marketing. Withdraw in the Privacy Centre without accepting another notice.');
  response=page.waitForResponse(r=>r.url().endsWith('/admin/notices')&&r.request().method()==='POST');await form.getByRole('button',{name:'Create notice',exact:true}).click();received=await response;expect(received.status()).toBe(201);const notice=await received.json();
  await page.getByRole('button',{name:'Policies',exact:true}).click();form=page.locator('form').filter({has:page.getByRole('heading',{name:'Create policy draft',exact:true})});await form.getByLabel('Policy purpose').selectOption(purpose.id);await form.getByLabel('Notice version').selectOption(notice.version_id);await form.getByLabel('Policy condition').selectOption('AFFIRMATIVE_MARKETING_CONSENT');await form.getByRole('checkbox',{name:new RegExp(system.name)}).check();
  response=page.waitForResponse(r=>r.url().endsWith('/admin/policies')&&r.request().method()==='POST');await form.getByRole('button',{name:'Create policy draft',exact:true}).click();received=await response;expect(received.status()).toBe(201);const policy=await received.json();
  const reviewer=await browser.newContext();try{const review=await reviewer.newPage();await loginUi(review,h,'owner');await review.goto('/workspace/configuration');await review.getByRole('button',{name:'Policies',exact:true}).click();await review.getByLabel('Search policy versions').fill(policy.id);
    const card=review.locator('article').filter({has:review.getByRole('heading',{name:'Policy '+policy.id,exact:true})});await card.getByLabel('Publication authenticator code').fill(authenticatorCode(h.users.owner!.totp_uri!));const published=review.waitForResponse(r=>r.url().endsWith(`/policies/${policy.id}/publish`));await card.getByRole('button',{name:'Approve and publish exact version'}).click();expect((await published).status()).toBe(200);await expect(card.getByText('Published',{exact:true})).toBeVisible();
    await review.reload();await review.getByRole('button',{name:'Policies',exact:true}).click();await review.getByLabel('Search policy versions').fill(policy.id);await expect(review.getByText('Published',{exact:true})).toBeVisible();await h.screenshot(review,'configuration');
  }finally{await reviewer.close();}
  await page.goto('/workspace/principals');const mapping=page.locator('form').filter({has:page.getByRole('heading',{name:'Create target mapping',exact:true})});await mapping.getByLabel('Mapping principal').selectOption(h.users.alice!.principal_id!);await mapping.getByLabel('Mapping purpose').selectOption(purpose.id);await mapping.getByLabel('Mapping system').selectOption(system.id);const mapped=page.waitForResponse(r=>r.url().endsWith('/admin/target-mappings')&&r.request().method()==='POST');await mapping.getByRole('button',{name:'Create target mapping',exact:true}).click();expect((await mapped).status()).toBe(201);
});
