'use client';
import { useState, type ReactNode, type FormEvent } from 'react';
import type { schemas } from '@orvia/contracts';
import type { EndpointMap } from '../../../../packages/contracts/generated/endpoint-types.ts';
import { call, useCollection, useMutation } from './api.ts';
import { describeFailure, type UiFailure } from './errors.ts';
import { hasCapability, type StaffSession } from './session-context.tsx';
import { CONFIGURATION_STATUS_LABELS, formatTime } from './state-labels.ts';
import { FailureState, Freshness, NoticeBox, QueryBoundary, StateBadge, TextField } from './ui.tsx';

type CreateOperation = 'create_purposes'|'create_notices'|'create_policies'|'create_systems'|'create_principals'|'create_mapping';
const value=(form:FormData,key:string)=>String(form.get(key)??'');
export function Input({label,name,type='text',maxLength=120}:{label:string;name:string;type?:string;maxLength?:number}) {
  return <label className="field"><span className="label">{label}</span><input name={name} type={type} required maxLength={maxLength} /></label>;
}
export function Select({label,name,options}:{label:string;name:string;options:{id:string;name:string}[]}) {
  return <label className="field"><span className="label">{label}</span><select name={name} required defaultValue=""><option value="">Select…</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>;
}
export function MutationFeedback({mutation,onReplayed}:{mutation:{failure:UiFailure|null;status:string;unsettled:boolean;retry:()=>Promise<unknown>};onReplayed:()=>void}) {
  if(!mutation.failure)return null;
  return <><FailureState failure={mutation.failure} />{mutation.unsettled?<NoticeBox tone="warn" title="Original request preserved"><p>A current-state read does not settle this request. Stay on this page. Replay uses the same payload and key; no new mutation is allowed while its outcome is unresolved.</p>{mutation.failure.code!=='IDEMPOTENCY_CONFLICT'?<button type="button" disabled={mutation.status==='pending'} onClick={async()=>{if(await mutation.retry())onReplayed();}}>Replay original request</button>:<p>The server rejected conflicting key reuse. Preserve the request for operator investigation.</p>}</NoticeBox>:null}</>;
}
function CreateRecord<K extends CreateOperation>({operation,label,allowed,build,onSaved,children}:{operation:K;label:string;allowed:boolean;build:(form:FormData)=>EndpointMap[K]['request'];onSaved:()=>void;children:ReactNode}) {
  const mutation=useMutation(operation,true);
  const [localError,setLocalError]=useState<UiFailure|null>(null);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;setLocalError(null);try{const result=await mutation.run(build(new FormData(form)));if(result){form.reset();onSaved();}}catch(error){setLocalError(describeFailure(error));}};
  if(!allowed)return <NoticeBox tone="info" title="Read-only for this session"><p>Your current capabilities do not allow {label.toLowerCase()}.</p></NoticeBox>;
  return <form className="panel" onSubmit={submit}><h3>{label}</h3><fieldset disabled={mutation.status==='pending'||mutation.unsettled}>{children}<button className="primary" type="submit">{mutation.status==='pending'?'Recording…':label}</button></fieldset>{localError?<FailureState failure={localError}/>:null}<MutationFeedback mutation={mutation} onReplayed={onSaved}/>{mutation.result?<p role="status">Recorded <code>{mutation.result.id}</code>. <button type="button" onClick={mutation.newInteraction}>Start another request</button></p>:null}</form>;
}

export function Configuration({session}:{session:StaffSession}) {
  const [tab,setTab]=useState('purposes');
  const purposes=useCollection('list_purposes');const notices=useCollection('list_notices');
  const policies=useCollection('list_policies');const systems=useCollection('list_systems');
  const canWrite=hasCapability(session,'configuration.write');
  const selectors={legal_entity_id:session.scope.legal_entity_id,environment_id:session.scope.environment_id};
  const purposeOptions=purposes.data?.items.map(p=>({id:p.id,name:p.name}))??[];
  const systemOptions=systems.data?.items.map(s=>({id:s.id,name:s.name}))??[];
  const reload=()=>{purposes.refresh();notices.refresh();policies.refresh();systems.refresh();};
  return <><div className="page-head"><h2>Configuration</h2><p>Versioned purposes, notices, policies and allowlisted synthetic systems. Only distinct-reviewer policy publication publishes its notice.</p></div>
    <nav className="row" aria-label="Configuration sections">{['purposes','notices','policies','systems'].map(t=><button key={t} type="button" aria-pressed={tab===t} onClick={()=>setTab(t)}>{t[0]!.toUpperCase()+t.slice(1)}</button>)}</nav>
    {tab==='purposes'?<><Freshness query={purposes}/><QueryBoundary query={purposes} label="purposes" isEmpty={d=>!d.items.length}>{d=><RecordList label="Purpose versions" items={d.items} render={p=><><h3>{p.name}</h3><p><code>{p.id}</code> · {p.code} · version {p.version}</p><StateBadge dictionary={CONFIGURATION_STATUS_LABELS} value={p.status}/><p>{p.description}</p></>}/>}</QueryBoundary><CreateRecord operation="create_purposes" label="Create purpose" allowed={canWrite} onSaved={reload} build={f=>({...selectors,code:value(f,'code') as 'promotional_marketing'|'order_service_demo',name:value(f,'name'),description:value(f,'description')})}><Input label="Purpose name" name="name"/><Select label="Purpose condition" name="code" options={[{id:'promotional_marketing',name:'Promotional marketing'},{id:'order_service_demo',name:'Separate synthetic order service'}]}/><Input label="Description" name="description" maxLength={500}/></CreateRecord></>:null}
    {tab==='notices'?<><Freshness query={notices}/><QueryBoundary query={notices} label="notices" isEmpty={d=>!d.items.length}>{d=><RecordList label="Notice versions" items={d.items} render={n=><><h3>{n.title}</h3><p>Purpose <code>{n.purpose_id}</code> · version <code>{n.version_id}</code></p><p>{n.published_at?'Published '+formatTime(n.published_at):'Draft; publish through its policy'}</p><details><summary>Read notice content</summary><p className="notice-body">{n.content}</p><code>{n.content_digest}</code></details></>}/>}</QueryBoundary><QueryBoundary query={purposes} label="purpose choices">{()=> <CreateRecord operation="create_notices" label="Create notice" allowed={canWrite} onSaved={reload} build={f=>({purpose_id:value(f,'purpose_id'),language:'en',title:value(f,'title'),content:value(f,'content')})}><Select label="Notice purpose" name="purpose_id" options={purposeOptions}/><Input label="Notice title" name="title"/><label className="field"><span className="label">Notice content</span><textarea name="content" required maxLength={10000}/></label></CreateRecord>}</QueryBoundary></>:null}
    {tab==='policies'?<><Freshness query={policies}/><QueryBoundary query={policies} label="policies" isEmpty={d=>!d.items.length}>{d=><RecordList label="Policy versions" items={d.items} render={p=><PolicyCard policy={p} session={session} onSaved={reload}/>}/>}</QueryBoundary><QueryBoundary query={purposes} label="policy purposes">{()=> <QueryBoundary query={notices} label="policy notices">{()=> <QueryBoundary query={systems} label="policy systems">{()=> <CreateRecord operation="create_policies" label="Create policy draft" allowed={canWrite} onSaved={reload} build={f=>({purpose_id:value(f,'purpose_id'),notice_version_id:value(f,'notice_version_id'),condition:value(f,'condition') as 'AFFIRMATIVE_MARKETING_CONSENT'|'APPROVED_SYNTHETIC_ORDER_SERVICE',system_ids:f.getAll('system_ids').map(String),required_observation:true})}><Select label="Policy purpose" name="purpose_id" options={purposeOptions}/><Select label="Notice version" name="notice_version_id" options={notices.data!.items.map(n=>({id:n.version_id,name:n.title+' · '+n.version_id}))}/><Select label="Policy condition" name="condition" options={[{id:'AFFIRMATIVE_MARKETING_CONSENT',name:'Affirmative marketing consent'},{id:'APPROVED_SYNTHETIC_ORDER_SERVICE',name:'Independent synthetic order-service condition'}]}/><fieldset><legend>Systems (one to three)</legend>{systemOptions.map(s=><label className="checkbox" key={s.id}><input name="system_ids" type="checkbox" value={s.id}/>{s.name} · {s.id}</label>)}</fieldset><p>Supported automated obligations require independent observation. Manual targets remain explicit manual obligations.</p></CreateRecord>}</QueryBoundary>}</QueryBoundary>}</QueryBoundary></>:null}
    {tab==='systems'?<><Freshness query={systems}/><QueryBoundary query={systems} label="systems" isEmpty={d=>!d.items.length}>{d=><RecordList label="Configured systems" items={d.items} render={s=><SystemCard system={s} session={session} onSaved={reload}/>}/>}</QueryBoundary><CreateRecord operation="create_systems" label="Create synthetic system" allowed={canWrite} onSaved={reload} build={f=>({...selectors,name:value(f,'name'),connector:value(f,'connector') as 'SYNTHETIC_CRM'|'ORVIA_REST_SIMULATOR'|'LEGACY_MANUAL'})}><Input label="System name" name="name"/><Select label="Connector" name="connector" options={[{id:'SYNTHETIC_CRM',name:'Synthetic CRM'},{id:'ORVIA_REST_SIMULATOR',name:'Local REST simulator'},{id:'LEGACY_MANUAL',name:'Legacy manual obligation'}]}/></CreateRecord></>:null}
  </>;
}

function PolicyCard({policy,session,onSaved}:{policy:ReturnType<typeof schemas.Policy.parse>;session:StaffSession;onSaved:()=>void}) {
  const publish=useMutation('publish_policy',true);const [code,setCode]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<UiFailure|null>(null);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(busy)return;setBusy(true);setError(null);try{const proof=await call('reauthenticate_policy',{version_id:policy.version_id,digest:policy.digest,code},{params:{id:policy.id}});setCode('');if(await publish.run({version_id:policy.version_id,digest:policy.digest,reauthentication_id:proof.reauthentication_id},{params:{id:policy.id}}))onSaved();}catch(error){setError(describeFailure(error,{write:true}));}finally{setBusy(false);setCode('');}};
  return <><h3>Policy {policy.id}</h3><StateBadge dictionary={CONFIGURATION_STATUS_LABELS} value={policy.status}/><p>Purpose <code>{policy.purpose_id}</code> · author <code>{policy.author_id}</code></p><p>Exact version <code>{policy.version_id}</code><br/>Digest <code>{policy.digest}</code></p><p>{policy.condition} · independent observation {policy.required_observation?'required':'not required by this policy'}</p><p>Systems {policy.system_ids.join(', ')}</p>{policy.status==='DRAFT'&&hasCapability(session,'policy.publish')?(policy.author_id===session.actor_id?<NoticeBox tone="info" title="Distinct reviewer required"><p>The author cannot publish their own policy.</p></NoticeBox>:<form onSubmit={submit}><TextField label="Publication authenticator code" value={code} onChange={setCode} inputMode="numeric" maxLength={6} required autoComplete="one-time-code"/><button type="submit" disabled={busy||publish.unsettled||code.length!==6}>Approve and publish exact version</button></form>):null}{error?<FailureState failure={error}/>:null}<MutationFeedback mutation={publish} onReplayed={onSaved}/>{publish.result?<p role="status">Policy publication recorded.</p>:null}</>;
}
function SystemCard({system,session,onSaved}:{system:ReturnType<typeof schemas.System.parse>;session:StaffSession;onSaved:()=>void}) {
  const check=useMutation('check_system',false);
  return <><h3>{system.name}</h3><p><code>{system.id}</code> · {system.connector} · capability {system.capability_version}</p><p>Declared restriction {String(system.supports_restrict)} · declared read {String(system.supports_read)}</p><p>Last capability check: {formatTime(system.checked_at)}. A capability check is not an effect observation.</p>{hasCapability(session,'systems.check')?<button type="button" disabled={check.status==='pending'} onClick={async()=>{if(await check.run(undefined,{params:{id:system.id}}))onSaved();}}>Check system capability</button>:null}{check.failure?<FailureState failure={check.failure}/>:null}</>;
}

export function RecordList<T extends {id:string}>({label,items,render}:{label:string;items:T[];render:(item:T)=>ReactNode}) {
  const [page,setPage]=useState(0);const [filter,setFilter]=useState('');
  const filtered=items.filter(item=>JSON.stringify(item).toLowerCase().includes(filter.toLowerCase()));const current=Math.min(page,Math.max(0,Math.ceil(filtered.length/10)-1));
  return <section aria-label={label}><TextField label={'Search '+label.toLowerCase()} value={filter} onChange={value=>{setFilter(value);setPage(0);}}/><p>{filtered.length} recorded result(s). Page {current+1}.</p>{filtered.slice(current*10,current*10+10).map(item=><article className="panel" key={item.id}>{render(item)}</article>)}{!filtered.length?<p>No matching records.</p>:null}<div className="row"><button type="button" disabled={current===0} onClick={()=>setPage(current-1)}>Previous records</button><button type="button" disabled={(current+1)*10>=filtered.length} onClick={()=>setPage(current+1)}>Next records</button></div></section>;
}

export function Principals({session}:{session:StaffSession}) {
  const principals=useCollection('list_principals');const purposes=useCollection('list_purposes',{enabled:hasCapability(session,'configuration.read')});const systems=useCollection('list_systems',{enabled:hasCapability(session,'configuration.read')});const mappings=useCollection('list_mappings',{enabled:hasCapability(session,'configuration.read')});
  const scope={legal_entity_id:session.scope.legal_entity_id,environment_id:session.scope.environment_id};
  return <><div className="page-head"><h2>Principals and target mappings</h2><p>Directory references are scoped to this organisation. Creating a reference does not create a login account.</p></div><Freshness query={principals}/><QueryBoundary query={principals} label="principal directory" isEmpty={d=>!d.items.length}>{d=><RecordList label="Principals" items={d.items} render={p=><><h3>{p.display_name}</h3><p>{p.email} · <code>{p.id}</code></p><p>Synthetic record</p></>}/>}</QueryBoundary><CreateRecord operation="create_principals" label="Create principal reference" allowed={hasCapability(session,'principals.create')} onSaved={principals.refresh} build={f=>({...scope,display_name:value(f,'display_name'),email:value(f,'email')})}><Input label="Display name" name="display_name" maxLength={100}/><Input label="Synthetic email" name="email" type="email" maxLength={254}/><p>Use only reserved aster.example or birch.example addresses.</p></CreateRecord>
    {hasCapability(session,'configuration.read')?<><h3>Exact target mappings</h3><Freshness query={mappings}/><QueryBoundary query={mappings} label="target mappings" isEmpty={d=>!d.items.length}>{d=><RecordList label="Mappings" items={d.items} render={m=><><h4>Mapping {m.id}</h4><p>Principal {m.principal_id} · purpose {m.purpose_id} · system {m.system_id}</p><p>Target {m.target_subject_reference} · generation {m.target_generation}</p></>}/>}</QueryBoundary><QueryBoundary query={principals} label="mapping principals">{p=><QueryBoundary query={purposes} label="mapping purposes">{pur=><QueryBoundary query={systems} label="mapping systems">{sys=><CreateRecord operation="create_mapping" label="Create target mapping" allowed={hasCapability(session,'configuration.write')} onSaved={mappings.refresh} build={f=>({principal_id:value(f,'principal_id'),purpose_id:value(f,'purpose_id'),system_id:value(f,'system_id')})}><Select label="Mapping principal" name="principal_id" options={p.items.map(x=>({id:x.id,name:x.display_name+' · '+x.email}))}/><Select label="Mapping purpose" name="purpose_id" options={pur.items.map(x=>({id:x.id,name:x.name}))}/><Select label="Mapping system" name="system_id" options={sys.items.map(x=>({id:x.id,name:x.name}))}/><p>The server creates the exact synthetic target identity; no arbitrary target identifiers or URLs.</p></CreateRecord>}</QueryBoundary>}</QueryBoundary>}</QueryBoundary></>:null}
  </>;
}
