import type { Context, Page } from '../../domain/src/shared/transaction.ts';
import type { OperationsEnv } from '../../domain/src/operations/shared.ts';
import type { RouteDefinition } from '../../../shared/contracts/src/index.ts';
import { createTemplate, publishTemplate, templateList, createAssessment, assessmentView, assessmentList, recordAnswers, submitAssessment, decideAssessment, reviseAssessment, createFinding, recordFindingEvent, escalationSweep } from '../../domain/src/assessments/impact.ts';
import { createAgreement, terminateAgreement, agreementList, setTier, standing, standingList, createSupplierLink, revokeSupplierLink, supplierLinkList } from '../../domain/src/third-party/third-party.ts';
import { createPolicy, decidePolicy, acknowledgePolicy, policyList, createIssue, readIssue, recordIssueEvent, issueList, importRegulatoryFramework, createControlTest, controlTestDetail, controlTestList, runControlTest, toggleControlTest, controlTestSweep, alertList, complianceReport } from '../../domain/src/grc/lifecycle.ts';
import { ropaEntries, ropaEntry, ropaSummary, ropaImpact, declareLocation, locationList, createRopaVersion, approveRopaVersion, ropaVersionList, ropaDiff } from '../../domain/src/mapping/ropa.ts';
import { createExport, advanceExport, stopExport, exportView, exportList, exportChunk } from '../../domain/src/exports/exports.ts';
import { preparePackage, reviewPackage, releasePackage, revokePackage, withdrawPackage, packageView, packageList, collectOwnPackage } from '../../domain/src/rights/response-packages.ts';
import { requestRun, runDetail, runList, recordLabels, labelSet, measureQuality, qualityList, exposureList } from '../../domain/src/discovery/classification.ts';
import { createTransport, enableTransport, disableTransport, revealSigningSecret, transportList, createRouting, decideRouting, routingList, composeMessage, reviewMessage, cancelMessage, messageDetail, messageList } from '../../domain/src/delivery/delivery.ts';
import { createTopic, retireTopic, topicList, principalCentre, ownCentre, decision as preferenceDecision, recordOwnChoice } from '../../domain/src/preferences/preferences.ts';
import { createSite, enableSite, disableSite, siteList, createConfig, decideConfig, configList, consentStats, requestScan, scanList } from '../../domain/src/cmp/cmp.ts';

/**
 * Dispatch for the expanded V1 delivery families. Every route arrives already
 * authenticated, capability-checked, validated and inside the scoped business
 * transaction; returning undefined passes the route on.
 */
export async function expansionRoute(c: Context, route: RouteDefinition, id: string | undefined, input: unknown, page: Page, query: unknown, env: OperationsEnv): Promise<unknown | undefined> {
  switch (route.id) {
    case 'list_impact_templates': return templateList(c, page);
    case 'create_impact_template': return createTemplate(c, input);
    case 'publish_impact_template': return publishTemplate(c, id!, input);
    case 'list_impact_assessments': return assessmentList(c, page, query);
    case 'create_impact_assessment': return createAssessment(c, input);
    case 'impact_assessment': return assessmentView(c, id!);
    case 'answer_impact_assessment': return recordAnswers(c, id!, input);
    case 'submit_impact_assessment': return submitAssessment(c, id!);
    case 'decide_impact_assessment': return decideAssessment(c, id!, input);
    case 'revise_impact_assessment': return reviseAssessment(c, id!, input);
    case 'create_impact_finding': return createFinding(c, id!, input);
    case 'record_impact_finding_event': return recordFindingEvent(c, id!, input);
    case 'impact_escalation_sweep': return escalationSweep(c);
    case 'list_processor_agreements': return agreementList(c, page, query);
    case 'create_processor_agreement': return createAgreement(c, input);
    case 'terminate_processor_agreement': return terminateAgreement(c, id!, input);
    case 'set_processor_tier': return setTier(c, id!, input);
    case 'third_party_standing': return standing(c, id!);
    case 'list_third_party_standing': return standingList(c, page);
    case 'create_supplier_link': return createSupplierLink(c, input);
    case 'list_supplier_links': return supplierLinkList(c, page, query);
    case 'revoke_supplier_link': return revokeSupplierLink(c, id!, input);
    case 'list_grc_policies': return policyList(c, page);
    case 'create_grc_policy': return createPolicy(c, input);
    case 'decide_grc_policy': return decidePolicy(c, id!, input);
    case 'acknowledge_grc_policy': return acknowledgePolicy(c, id!);
    case 'list_grc_issues': return issueList(c, page, query);
    case 'create_grc_issue': return createIssue(c, input);
    case 'grc_issue': return readIssue(c, id!);
    case 'record_grc_issue_event': return recordIssueEvent(c, id!, input);
    case 'import_regulatory_framework': return importRegulatoryFramework(c, input);
    case 'list_control_tests': return controlTestList(c, page);
    case 'create_control_test': return createControlTest(c, input);
    case 'control_test': return controlTestDetail(c, id!);
    case 'run_control_test': return runControlTest(c, id!);
    case 'toggle_control_test': return toggleControlTest(c, id!, input);
    case 'control_test_sweep': return controlTestSweep(c);
    case 'list_compliance_alerts': return alertList(c, page);
    case 'compliance_report': return complianceReport(c);
    case 'list_system_locations': return locationList(c, id!, page);
    case 'declare_system_location': return declareLocation(c, id!, input);
    case 'list_ropa_entries': return ropaEntries(c, page);
    case 'ropa_entry': return ropaEntry(c, id!);
    case 'ropa_summary': return ropaSummary(c);
    case 'ropa_impact': return ropaImpact(c, query);
    case 'list_ropa_versions': return ropaVersionList(c, page);
    case 'create_ropa_version': return createRopaVersion(c, input);
    case 'approve_ropa_version': return approveRopaVersion(c, id!, input);
    case 'ropa_version_diff': return ropaDiff(c, id!, query);
    case 'list_data_exports': return exportList(c, page);
    case 'create_data_export': return createExport(c, input);
    case 'data_export': return exportView(c, id!);
    case 'advance_data_export': return advanceExport(c, id!);
    case 'stop_data_export': return stopExport(c, id!);
    case 'data_export_chunk': return exportChunk(c, id!, query);
    case 'list_response_packages': return packageList(c, id!, page);
    case 'prepare_response_package': return preparePackage(c, env, id!);
    case 'response_package': return packageView(c, id!);
    case 'review_response_package': return reviewPackage(c, id!, input);
    case 'release_response_package': return releasePackage(c, id!, input);
    case 'revoke_response_package': return revokePackage(c, id!, input);
    case 'withdraw_response_package': return withdrawPackage(c, id!);
    case 'own_response_package': return collectOwnPackage(c, id!);
    case 'list_preference_topics': return topicList(c, page);
    case 'create_preference_topic': return createTopic(c, input);
    case 'retire_preference_topic': return retireTopic(c, id!);
    case 'principal_preferences': return principalCentre(c, id!);
    case 'preference_decision': return preferenceDecision(c, query);
    case 'own_preferences': return ownCentre(c);
    case 'set_own_preference': return recordOwnChoice(c, input);
    case 'request_classification_run': return requestRun(c, id!, input);
    case 'list_classification_runs': return runList(c, id!, page);
    case 'classification_run': return runDetail(c, id!);
    case 'label_classification': return recordLabels(c, id!, input);
    case 'classification_labels': return labelSet(c, id!);
    case 'measure_classification': return measureQuality(c, id!);
    case 'list_classification_quality': return qualityList(c, id!, page);
    case 'list_exposure_findings': return exposureList(c, page);
    case 'list_delivery_transports': return transportList(c, page);
    case 'create_delivery_transport': return createTransport(c, input);
    case 'enable_delivery_transport': return enableTransport(c, id!);
    case 'disable_delivery_transport': return disableTransport(c, id!, input);
    case 'reveal_transport_signing_secret': return revealSigningSecret(c, env, id!);
    case 'list_alert_routings': return routingList(c, page);
    case 'create_alert_routing': return createRouting(c, input);
    case 'decide_alert_routing': return decideRouting(c, id!, input);
    case 'list_outbound_messages': return messageList(c, page);
    case 'compose_outbound_message': return composeMessage(c, input);
    case 'outbound_message': return messageDetail(c, id!);
    case 'review_outbound_message': return reviewMessage(c, id!, input);
    case 'withdraw_outbound_message': return cancelMessage(c, id!);
    case 'list_cmp_sites': return siteList(c, page);
    case 'create_cmp_site': return createSite(c, input);
    case 'enable_cmp_site': return enableSite(c, id!);
    case 'disable_cmp_site': return disableSite(c, id!);
    case 'list_cmp_configs': return configList(c, id!, page);
    case 'create_cmp_config': return createConfig(c, id!, input);
    case 'decide_cmp_config': return decideConfig(c, id!, input);
    case 'cmp_consent_stats': return consentStats(c, id!);
    case 'list_cmp_scans': return scanList(c, id!, page);
    case 'request_cmp_scan': return requestScan(c, id!, input);
    default: return undefined;
  }
}
