import {grcRoute} from './grc-routes.ts';
import type { Context } from '../../domain/src/shared/transaction.ts';
import type { Page } from '@orvia/domain/transaction';
import type { RouteDefinition } from '../../../shared/contracts/src/index.ts';
import { createDataAsset, createCatalogAsset, dataAssetList, readDataAsset, tombstoneAsset, createActivity, activityList, createRelationship, relationshipList, graphSearch, neighbourhood, impact } from '../../domain/src/graph/graph.ts';
import { createTemplate, templateList, createNotificationTask, notificationTaskList, readNotificationTask, recordDelivery, escalationSweep } from '../../domain/src/notifications/notifications.ts';
import { createIncident, incidentList, incidentAssessment, correctIncident, containIncident, closeIncident, transitionNotification, createObligationRule, obligationRuleList } from '../../domain/src/incidents/incidents.ts';
import { createProcessor, processorList, linkProcessorSystem, recordCoordination, processorStanding, createAssessment, assessmentList, completeAssessment, createFinding, findingList, closeFinding } from '../../domain/src/processors/processors.ts';
import { coverageReport, deriveGaps, gapList, assignGap, closeGap, gapGuidance } from '../../domain/src/coverage/coverage.ts';
import { createConstraint, constraintList, createHold, holdList, releaseHold, evaluateEligibility, recordRetentionDecision, recordRetentionOutcome, retentionOutcomeList } from '../../domain/src/retention/retention.ts';
import { createRequest, requestList, readRequest, reviewIdentity, scopeRequest, transitionRequest, releaseResponse, recordOutcome, createMandate, mandateList, revokeMandate } from '../../domain/src/rights/rights.ts';
import { createAiSystem, aiSystemList, readAiSystem, recordAiEvent, aiGovernanceReport } from '../../domain/src/ai-governance/ai-governance.ts';
import { createCatalogTarget, catalogTargetList, catalogTargetDetail, approveCatalogTarget,disableCatalogTarget } from '../../domain/src/discovery/catalog.ts';

export async function governanceRoute(c: Context, route: RouteDefinition, id: string | undefined, input: unknown, page: Page, query: unknown): Promise<unknown | undefined> {
  const grc=await grcRoute(c,route.id,id,input,page);
  if(grc!==undefined)return grc;
  switch (route.id) {
    case 'list_catalog_discovery_targets':return catalogTargetList(c,page);
    case 'create_catalog_discovery_target':return createCatalogTarget(c,input);
    case 'catalog_discovery_target':return catalogTargetDetail(c,id!);
    case 'approve_catalog_discovery_target':return approveCatalogTarget(c,id!);
    case 'disable_catalog_discovery_target':return disableCatalogTarget(c,id!);
    case 'list_ai_systems':return aiSystemList(c,page);
    case 'create_ai_system':return createAiSystem(c,input);
    case 'ai_system':return readAiSystem(c,id!);
    case 'record_ai_event':return recordAiEvent(c,id!,input);
    case 'ai_governance_report':return aiGovernanceReport(c);
    case 'list_data_assets':return dataAssetList(c,page);
    case 'data_asset':return readDataAsset(c,id!);
    case 'create_data_asset':return createDataAsset(c,input);
    case 'create_catalog_asset':return createCatalogAsset(c,input);
    case 'tombstone_data_asset':return tombstoneAsset(c,id!,input);
    case 'list_activities':return activityList(c,page);
    case 'create_activity':return createActivity(c,input);
    case 'list_relationships':return relationshipList(c,page);
    case 'create_relationship':return createRelationship(c,input);
    case 'graph_search':return graphSearch(c,query);
    case 'graph_neighbourhood':return neighbourhood(c,id!,query);
    case 'graph_impact':return impact(c,id!);
    case 'list_rights_requests':return requestList(c,page);
    case 'create_rights_request':return createRequest(c,input);
    case 'rights_request':return readRequest(c,id!);
    case 'review_identity':return reviewIdentity(c,id!,input);
    case 'scope_request':return scopeRequest(c,id!,input);
    case 'transition_request':return transitionRequest(c,id!,input);
    case 'release_response':return releaseResponse(c,id!,input);
    case 'record_outcome':return recordOutcome(c,id!,input);
    case 'list_constraints':return constraintList(c,page);
    case 'create_constraint':return createConstraint(c,input);
    case 'list_holds':return holdList(c,page);
    case 'create_hold':return createHold(c,input);
    case 'release_hold':return releaseHold(c,id!,input);
    case 'asset_eligibility':return evaluateEligibility(c,id!);
    case 'retention_decision':return recordRetentionDecision(c,id!,input);
    case 'retention_outcome':return recordRetentionOutcome(c,id!,input);
    case 'list_retention_outcomes':return retentionOutcomeList(c,page);
    case 'coverage':return coverageReport(c);
    case 'list_gaps':return gapList(c,page);
    case 'derive_gaps':return deriveGaps(c);
    case 'assign_gap':return assignGap(c,id!,input);
    case 'close_gap':return closeGap(c,id!,input);
    case 'gap_guidance':return gapGuidance(c,id!);
    case 'list_processors':return processorList(c,page);
    case 'create_processor':return createProcessor(c,input);
    case 'link_processor_system':return linkProcessorSystem(c,id!,input);
    case 'processor_standing':return processorStanding(c,id!);
    case 'record_coordination':return recordCoordination(c,id!,input);
    case 'list_assessments':return assessmentList(c,page);
    case 'create_assessment':return createAssessment(c,input);
    case 'complete_assessment':return completeAssessment(c,id!,input);
    case 'list_findings':return findingList(c,page);
    case 'create_finding':return createFinding(c,input);
    case 'close_finding':return closeFinding(c,id!,input);
    case 'list_incidents':return incidentList(c,page);
    case 'create_incident':return createIncident(c,input);
    case 'incident_assessment':return incidentAssessment(c,id!);
    case 'correct_incident':return correctIncident(c,id!,input);
    case 'contain_incident':return containIncident(c,id!,input);
    case 'close_incident':return closeIncident(c,id!,input);
    case 'transition_notification':return transitionNotification(c,id!,input);
    case 'list_obligation_rules':return obligationRuleList(c,page);
    case 'create_obligation_rule':return createObligationRule(c,input);
    case 'list_templates':return templateList(c,page);
    case 'create_template':return createTemplate(c,input);
    case 'list_notification_tasks':return notificationTaskList(c,page);
    case 'create_notification_task':return createNotificationTask(c,input);
    case 'notification_task':return readNotificationTask(c,id!);
    case 'record_delivery':return recordDelivery(c,id!,input);
    case 'escalation_sweep':return escalationSweep(c);
    case 'list_mandates':return mandateList(c,page);
    case 'create_mandate':return createMandate(c,input);
    case 'revoke_mandate':return revokeMandate(c,id!,input);
    default: return undefined;
  }
}
