import type { Context, Page } from '../../domain/src/shared/transaction.ts';
import type { RouteDefinition } from '../../../shared/contracts/src/index.ts';
import type { OperationsEnv } from '../../domain/src/operations/shared.ts';
import { importPackage, decidePackage, packageList, packageDetail, activePackage, impactList, reviewImpact } from '../../domain/src/regulatory/packages.ts';
import { evaluateApplicability, applicabilityList, overrideApplicability } from '../../domain/src/regulatory/applicability.ts';
import { organisationProfile, setOrganisationProfile, completeSdfObligation } from '../../domain/src/registry/organisation.ts';
import { createPrincipalCategory, principalCategoryList, createDataCategory, dataCategoryList, createSubject, addSubjectReference, subjectView, subjectList, subjectProcessing, mergeSubject, unmergeSubject,
  createRelationship, endRelationship, createRepresentative, representativeList, verifyRepresentative, activateNomination, recordChildStatus, childStatus } from '../../domain/src/registry/principals.ts';
import { createPurpose, revisePurpose, purposeList, createCondition, conditionList, createSafeguard, safeguardList, createActivity, reviseActivity, linkActivity, closeLink, activityView, activityList } from '../../domain/src/registry/processing.ts';
import { createNotice, createNoticeVersion, publishNoticeVersion, noticeList, noticeAt, recordDelivery, deliveryList, portalNotices } from '../../domain/src/registry/notices.ts';
import { createConsentRecord, recordConsentEvent, consentRecordView, consentRecordList, syncPortalConsent } from '../../domain/src/registry/consent.ts';
import { createEngagement, terminateEngagement, recordDisposition, engagementList, createSharingLink, sharingList } from '../../domain/src/registry/processors.ts';
import { createRule, reviseRule, ruleList, createHold, releaseHold, holdList } from '../../domain/src/registry/retention.ts';
import { bindConnector, bindingList } from '../../domain/src/registry/connectors.ts';
import { createRightsRun, createRetentionRun, evaluateRun, decideRun, cancelRun, runView, runList, actionList } from '../../domain/src/operations/runs.ts';
import { executeRun } from '../../domain/src/operations/executor.ts';
import { evidenceList, eventList, evidencePackage } from '../../domain/src/operations/evidence.ts';
import { createJob, appendRows, processJob, replayErrors, jobList, readJob } from '../../domain/src/operations/bulk-import.ts';
import { registerBreach, updateBreach, completeBreachTask, breachView, breachList } from '../../domain/src/operations/breach.ts';
import { openCaseProfile, caseProfile, caseProfileList } from '../../domain/src/operations/cases.ts';
import { operationsAttention, operationsCoverage, notificationSweep } from '../../domain/src/operations/attention.ts';
import { ownRequestHistory } from '../../domain/src/rights/portal.ts';

/**
 * Dispatch for the regulatory core, the data & processing registry and the
 * operational workflows. Every route arrives here already authenticated,
 * capability-checked, validated and inside the scoped business transaction.
 */
export async function operationsRoute(c: Context, route: RouteDefinition, id: string | undefined, input: unknown, page: Page, query: unknown, env: OperationsEnv): Promise<unknown | undefined> {
  switch (route.id) {
    case 'list_regulatory_packages': return packageList(c, page);
    case 'import_regulatory_package': return importPackage(c, input);
    case 'regulatory_package': return packageDetail(c, id!);
    case 'decide_regulatory_package': return decidePackage(c, id!, input);
    case 'active_regulatory_package': return activePackage(c, query);
    case 'evaluate_applicability': return evaluateApplicability(c, input);
    case 'list_applicability_decisions': return applicabilityList(c, page);
    case 'override_applicability': return overrideApplicability(c, input);
    case 'list_regulatory_impacts': return impactList(c, page, query);
    case 'review_regulatory_impact': return reviewImpact(c, id!, input);
    case 'organisation_profile': return organisationProfile(c);
    case 'set_organisation_profile': return setOrganisationProfile(c, input);
    case 'complete_sdf_obligation': return completeSdfObligation(c, id!, input);
    case 'list_principal_categories': return principalCategoryList(c, page);
    case 'create_principal_category': return createPrincipalCategory(c, input);
    case 'list_data_categories': return dataCategoryList(c, page);
    case 'create_data_category': return createDataCategory(c, input);
    case 'list_data_principals': return subjectList(c, page, query);
    case 'create_data_principal': return createSubject(c, env, input);
    case 'data_principal': return subjectView(c, id!);
    case 'data_principal_processing': return subjectProcessing(c, id!);
    case 'add_data_principal_reference': return addSubjectReference(c, env, id!, input);
    case 'merge_data_principal': return mergeSubject(c, id!, input);
    case 'unmerge_data_principal': return unmergeSubject(c, id!, input);
    case 'create_relationship_context': return createRelationship(c, input);
    case 'end_relationship_context': return endRelationship(c, id!, input);
    case 'list_representatives': return representativeList(c, page);
    case 'create_representative': return createRepresentative(c, input);
    case 'verify_representative': return verifyRepresentative(c, id!, input);
    case 'activate_nomination': return activateNomination(c, id!, input);
    case 'record_child_status': return recordChildStatus(c, input);
    case 'child_status': return childStatus(c, id!);
    case 'list_registry_purposes': return purposeList(c, page);
    case 'create_registry_purpose': return createPurpose(c, input);
    case 'revise_registry_purpose': return revisePurpose(c, id!, input);
    case 'list_processing_conditions': return conditionList(c, page);
    case 'create_processing_condition': return createCondition(c, input);
    case 'list_security_safeguards': return safeguardList(c, page);
    case 'create_security_safeguard': return createSafeguard(c, input);
    case 'list_registry_activities': return activityList(c, page, query);
    case 'create_registry_activity': return createActivity(c, input);
    case 'registry_activity': return activityView(c, id!);
    case 'revise_registry_activity': return reviseActivity(c, id!, input);
    case 'link_registry_activity': return linkActivity(c, id!, input);
    case 'close_activity_link': return closeLink(c, id!, input);
    case 'list_registry_notices': return noticeList(c, page);
    case 'create_registry_notice': return createNotice(c, input);
    case 'create_notice_version': return createNoticeVersion(c, id!, input);
    case 'publish_notice_version': return publishNoticeVersion(c, id!, input);
    case 'notice_at_time': return noticeAt(c, id!, query);
    case 'list_notice_deliveries': return deliveryList(c, page);
    case 'record_notice_delivery': return recordDelivery(c, input);
    case 'list_consent_records': return consentRecordList(c, page);
    case 'create_consent_record': return createConsentRecord(c, input);
    case 'consent_record': return consentRecordView(c, id!);
    case 'record_consent_event': return recordConsentEvent(c, id!, input);
    case 'sync_portal_consent': return syncPortalConsent(c);
    case 'list_processor_engagements': return engagementList(c, page, query);
    case 'create_processor_engagement': return createEngagement(c, input);
    case 'terminate_processor_engagement': return terminateEngagement(c, id!, input);
    case 'record_engagement_disposition': return recordDisposition(c, id!, input);
    case 'list_data_sharing_links': return sharingList(c, page, query);
    case 'create_data_sharing_link': return createSharingLink(c, input);
    case 'list_retention_rules': return ruleList(c, page);
    case 'create_retention_rule': return createRule(c, input);
    case 'revise_retention_rule': return reviseRule(c, id!, input);
    case 'list_retention_holds': return holdList(c, page, query);
    case 'create_retention_hold': return createHold(c, input);
    case 'release_retention_hold': return releaseHold(c, id!, input);
    case 'list_connector_bindings': return bindingList(c, page);
    case 'bind_connector': return bindConnector(c, input);
    case 'list_workflow_runs': return runList(c, page, query);
    case 'workflow_run': return runView(c, id!);
    case 'list_run_actions': return actionList(c, id!, page, query);
    case 'create_rights_run': return createRightsRun(c, input);
    case 'create_retention_run': return createRetentionRun(c, input);
    case 'evaluate_run': return evaluateRun(c, id!, input);
    case 'decide_run': return decideRun(c, id!, input);
    case 'execute_run': return executeRun(c, env, id!, input);
    case 'cancel_run': return cancelRun(c, id!, input);
    case 'run_evidence_package': return evidencePackage(c, id!);
    case 'list_evidence_records': return evidenceList(c, page, query);
    case 'list_operational_events': return eventList(c, page);
    case 'list_bulk_jobs': return jobList(c, page);
    case 'create_bulk_job': return createJob(c, input);
    case 'bulk_job': return readJob(c, id!);
    case 'append_bulk_job_rows': return appendRows(c, id!, input);
    case 'process_bulk_job': return processJob(c, env, id!, input);
    case 'replay_bulk_job_errors': return replayErrors(c, id!);
    case 'list_breaches': return breachList(c, page);
    case 'register_breach': return registerBreach(c, input);
    case 'breach': return breachView(c, id!);
    case 'update_breach': return updateBreach(c, id!, input);
    case 'complete_breach_task': return completeBreachTask(c, id!, input);
    case 'list_case_profiles': return caseProfileList(c, page);
    case 'open_case_profile': return openCaseProfile(c, id!, input);
    case 'case_profile': return caseProfile(c, id!);
    case 'operations_attention': return operationsAttention(c);
    case 'operations_coverage': return operationsCoverage(c);
    case 'operations_notification_sweep': return notificationSweep(c);
    case 'portal_notices': return portalNotices(c, page, query);
    case 'own_rights_request_history': return ownRequestHistory(c, id!, page);
    default: return undefined;
  }
}
