import type { Context } from '../../domain/src/shared/transaction.ts';
import type { Page } from '@orvia/domain/transaction';
import type { RouteDefinition } from '../../../shared/contracts/src/index.ts';
import type { runtime } from './runtime.ts';
import { importLicence, entitlementReport } from '../../domain/src/licensing/licensing.ts';
import { createSupportCase, supportCaseList, readSupportCase, recordResolution, registerCanary, canaryList, generateDiagnostic, approveDiagnostic, recordTransfer, validateIngressSubmission } from '../../domain/src/support/support.ts';
import { importRelease, releaseList, updateEligibility, planUpdate, readUpdatePlan, updatePlanList, recordUpdateStep, installationVersionList } from '../../domain/src/updates/updates.ts';
import { operationalReadiness } from '../../domain/src/monitoring/monitoring.ts';
import { auditEventList, exportAuditEvents, auditCoverage, correctAuditEvent } from '../../domain/src/audit/audit.ts';
import { noticeAvailability, setPreferredLanguage, recordNoticeRevision, noticeRevisionList } from '../../domain/src/notices/languages.ts';
import { preflight } from '../../domain/src/onboarding/preflight.ts';
import { declareSnapshot, snapshotList, startRestore, readRestore, restoreList, acknowledgeConflict, releaseRestore } from '../../domain/src/monitoring/restore.ts';
import { vendorVisibility } from '../../domain/src/monitoring/vendor.ts';
import { auditRetention, setAuditRetention } from '../../domain/src/audit/retention.ts';
import { submitImport, importList, readImport, decideImportRow, applyImport, purgeImport } from '../../domain/src/onboarding/imports.ts';
import { report } from '../../domain/src/reporting/reports.ts';
import { raiseOwnRightsRequest, ownRightsRequests, ownRightsRequest } from '../../domain/src/rights/portal.ts';
import { connectionList, readGuidedConnection, startConnection, recordConnectivity, recordScopedIdentity, approveResources, changeEnablement } from '../../domain/src/onboarding/connection.ts';

export async function platformRoute(c: Context, route: RouteDefinition, id: string | undefined, input: unknown, page: Page, query: unknown, r: ReturnType<typeof runtime>): Promise<unknown | undefined> {
  switch (route.id) {
    case 'entitlements':return entitlementReport(c);
    case 'import_licence':return importLicence(c,input,r.config.installation_id);
    case 'list_support_cases':return supportCaseList(c,page);
    case 'create_support_case':return createSupportCase(c,input);
    case 'support_case':return readSupportCase(c,id!);
    case 'generate_diagnostic':return generateDiagnostic(c,id!,r.config.installation_id);
    case 'record_resolution':return recordResolution(c,id!,input);
    case 'approve_diagnostic':return approveDiagnostic(c,id!,input);
    case 'record_transfer':return recordTransfer(c,id!,input);
    case 'validate_submission':return validateIngressSubmission(c,input);
    case 'list_canaries':return canaryList(c,page);
    case 'register_canary':return registerCanary(c,input);
    case 'list_releases':return releaseList(c,page);
    case 'import_release':return importRelease(c,input);
    case 'update_eligibility':return updateEligibility(c,id!);
    case 'plan_update':return planUpdate(c,id!,input);
    case 'update_plan':return readUpdatePlan(c,id!);
    case 'list_update_plans':return updatePlanList(c,page);
    case 'record_update_step':return recordUpdateStep(c,id!,input);
    case 'installation_versions':return installationVersionList(c,page);
    case 'operational_readiness':return operationalReadiness(c);
    case 'list_audit_events':return auditEventList(c,page,query);
    case 'export_audit_events':return exportAuditEvents(c,query);
    case 'audit_coverage':return auditCoverage(c);
    case 'correct_audit_event':return correctAuditEvent(c,input);
    case 'preflight':return preflight(c,r.config);
    case 'list_backup_snapshots':return snapshotList(c,page);
    case 'declare_snapshot':return declareSnapshot(c,input);
    case 'start_restore':return startRestore(c,input);
    case 'list_restore_runs':return restoreList(c,page);
    case 'vendor_visibility':return vendorVisibility(c);
    case 'audit_retention':return auditRetention(c);
    case 'set_audit_retention':return setAuditRetention(c,input);
    case 'report':return report(c,query);
    case 'own_rights_requests':return ownRightsRequests(c,page);
    case 'raise_own_rights_request':return raiseOwnRightsRequest(c,input);
    case 'own_rights_request':return ownRightsRequest(c,id!);
    case 'list_imports':return importList(c,page);
    case 'submit_import':return submitImport(c,input);
    case 'import_batch':return readImport(c,id!);
    case 'decide_import_row':return decideImportRow(c,id!,input);
    case 'apply_import':return applyImport(c,id!);
    case 'purge_import':return purgeImport(c,id!,input);
    case 'restore_run':return readRestore(c,id!);
    case 'acknowledge_conflict':return acknowledgeConflict(c,id!,input);
    case 'release_restore':return releaseRestore(c,id!);
    case 'list_connections':return connectionList(c,page);
    case 'start_connection':return startConnection(c,input);
    case 'connection':return readGuidedConnection(c,id!);
    case 'record_connectivity':return recordConnectivity(c,id!,input);
    case 'record_scoped_identity':return recordScopedIdentity(c,id!,input);
    case 'approve_resources':return approveResources(c,id!,input);
    case 'change_enablement':return changeEnablement(c,id!,input);
    case 'record_notice_revision':return recordNoticeRevision(c,id!,input);
    case 'list_notice_revisions':return noticeRevisionList(c,id!,page);
    case 'notice_languages':return noticeAvailability(c,id!,(query as {language?:string}|undefined)?.language??'en');
    case 'set_language':return setPreferredLanguage(c,input);
    default: return undefined;
  }
}
