import { createHash, randomUUID } from 'node:crypto';
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, extname, isAbsolute, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const roots = ['services', 'backend', 'shared', 'scripts', 'connectors', 'database', 'packages'];
const configs = ['pnpm-lock.yaml', 'pnpm-workspace.yaml', 'tsconfig.json', 'package.json'];
const required = ['services/worker/src/withdrawal-workflows.ts', 'services/worker/src/workflow-bundle.ts', 'scripts/build-worker-workflows.ts'];
const ignored = new Set(['node_modules', 'dist', '.next', '.git', '.local', '.worktrees']);
const extensions = new Set(['.ts', '.tsx', '.js', '.mjs', '.cjs', '.json', '.yaml', '.yml']);
const sha = (bytes: Buffer | string) => createHash('sha256').update(bytes).digest('hex');
const refuse = () => { throw new Error('Worker workflow bundle input validation failed'); };
function localPath(path: string) {
  const name = relative(root, path).replaceAll('\\', '/');
  if (!name || isAbsolute(name) || name.startsWith('../') || name.split('/').some(p => ignored.has(p)) ||
      !(configs.includes(name) || roots.some(prefix => name.startsWith(prefix + '/')))) refuse();
  if (lstatSync(path).isSymbolicLink() || !lstatSync(path).isFile() || realpathSync(path) !== resolve(path)) refuse();
  return name;
}
function snapshot() {
  const files = new Map<string, string>();
  function visit(path: string) {
    const stat = lstatSync(path);
    if (stat.isSymbolicLink()) refuse();
    if (stat.isDirectory()) {
      for (const entry of readdirSync(path).sort()) if (!ignored.has(entry)) visit(resolve(path, entry));
    } else if (stat.isFile() && extensions.has(extname(path))) {
      if (stat.size > 8 * 1024 * 1024) refuse();
      files.set(localPath(path), sha(readFileSync(path)));
    }
  }
  for (const prefix of roots) if (existsSync(resolve(root, prefix))) visit(resolve(root, prefix));
  for (const path of configs) files.set(path, sha(readFileSync(resolve(root, path))));
  return files;
}

interface Compilation { fileDependencies: Iterable<string> }
interface Compiler { hooks: { afterCompile: { tap(name: string, callback: (compilation: Compilation) => void): void } } }
interface WebpackConfig { plugins?: unknown[] }
interface Bundler {
  bundleWorkflowCode(options: { workflowsPath: string; webpackConfigHook(config: WebpackConfig): WebpackConfig }): Promise<{ code: string }>;
}

/** Explicit build-time compilation; runtime loaders must never compile as fallback. */
export async function buildWorkerWorkflows() {
  const require = createRequire(new URL('../services/worker/package.json', import.meta.url));
  const sdk = require('@temporalio/worker') as Bundler;
  const sdkPackage = JSON.parse(readFileSync(resolve(dirname(require.resolve('@temporalio/worker')), '../package.json'), 'utf8')) as { name?: unknown; version?: unknown };
  if (sdkPackage.name !== '@temporalio/worker' || typeof sdkPackage.version !== 'string') refuse();
  const sdkVersion = sdkPackage.version;
  const before = snapshot();
  const dependencies = new Set<string>([...required, ...configs, 'services/worker/package.json']);
  for (const path of dependencies) if (!before.has(path)) refuse();
  let compiled = false;
  const entry = resolve(root, required[0]!);
  const virtualEntry = resolve(dirname(entry), 'withdrawal-workflows-autogenerated-entrypoint.cjs');
  const bundle = await sdk.bundleWorkflowCode({
    workflowsPath: entry,
    webpackConfigHook(config) {
      config.plugins = [...(config.plugins ?? []), {
        apply(compiler: Compiler) {
          compiler.hooks.afterCompile.tap('OrviaWorkflowInputInventory', compilation => {
            compiled = true;
            for (const dependency of compilation.fileDependencies) {
              const path = resolve(dependency);
              if (path === virtualEntry && !existsSync(path)) continue;
              // Installed SDK/dependency bytes are represented by the frozen lockfile
              // and exact SDK version; customer-local source is enumerated separately.
              if (path.split(/[\\/]/).includes('node_modules')) continue;
              if (!existsSync(path)) refuse();
              const stat = lstatSync(path);
              if (stat.isDirectory()) continue;
              const name = localPath(path);
              if (!before.has(name) || before.get(name) !== sha(readFileSync(path))) refuse();
              dependencies.add(name);
            }
          });
        },
      }];
      return config;
    },
  });
  if (!compiled || dependencies.size > 512) refuse();
  const inputFiles = [...dependencies].sort().map(path => {
    const absolute = resolve(root, path);
    localPath(absolute);
    const hash = sha(readFileSync(absolute));
    if (before.get(path) !== hash) refuse();
    return { path, sha256: hash };
  });
  if (!bundle.code.length || Buffer.byteLength(bundle.code) > 8 * 1024 * 1024) refuse();
  const codeHash = sha(bundle.code);
  const metadata = JSON.stringify({ version: 1, sdk_version: sdkVersion, node_version: process.version,
    lockfile_sha256: before.get('pnpm-lock.yaml'), code_sha256: codeHash, input_files: inputFiles }, null, 2) + '\n';
  if (Buffer.byteLength(metadata) > 256 * 1024) refuse();
  const directory = resolve(root, 'services/worker/dist');
  mkdirSync(directory, { recursive: true });
  if (lstatSync(directory).isSymbolicLink() || realpathSync(directory) !== directory) refuse();
  const codePath = resolve(directory, codeHash + '.cjs');
  if (existsSync(codePath)) {
    if (lstatSync(codePath).isSymbolicLink() || sha(readFileSync(codePath)) !== codeHash) refuse();
  } else writeFileSync(codePath, bundle.code, { flag: 'wx' });
  const temporary = resolve(directory, 'workflow-bundle.' + randomUUID() + '.tmp');
  try {
    writeFileSync(temporary, metadata, { flag: 'wx' });
    renameSync(temporary, resolve(directory, 'workflow-bundle.json'));
  } finally { if (existsSync(temporary)) unlinkSync(temporary); }
  return { code_sha256: codeHash, input_files: inputFiles.length, sdk_version: sdkVersion };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await buildWorkerWorkflows();
  console.log('Worker workflow bundle built and input identity recorded.');
}
