import { existsSync,readdirSync,readFileSync,writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
const base='e5cdef310d61a697edcf9e4f7bc03c9a4a0a3e8c';
function git(args){const result=spawnSync('git',args,{encoding:'utf8',windowsHide:true});if(result.status!==0)throw new Error('Git index command failed');return result.stdout.trim();}
const directory='handoffs/codex';
const reports=readdirSync(`${directory}/artifacts`).filter(p=>p.endsWith('.json')).map(path=>({path:`${directory}/artifacts/${path}`,body:JSON.parse(readFileSync(`${directory}/artifacts/${path}`,'utf8').replace(/^\uFEFF/,''))}));
const commands=reports.filter(r=>Array.isArray(r.body.command)&&'exit_code'in r.body).map(({path,body:r})=>({artifact:path,command:r.command,started_at:r.started_at,finished_at:r.finished_at,exit_code:r.exit_code,result:r.result,source_commit:r.source_commit,source_tree_sha256:r.source_tree_sha256,log:r.artifact_paths})).sort((a,b)=>a.started_at.localeCompare(b.started_at));
writeFileSync(`${directory}/A00-command-index.json`,JSON.stringify({task_id:'A00',base_commit:base,commands,not_run:[{command:['node','scripts/record.mjs','audit','--json'],reason:'Automatic approval review rejected private lockfile metadata egress to public advisory service. No process exit code; not executed.'}],additional_tool_observations:[{action:'Workspace tool bootstrap and public version resolution',outcome:'Completed; pinned versions and source integrity recorded in toolchain.lock.json; no separate raw transcript was saved.'},{action:'Read-only repository/source/machine and Docker inspection',outcome:'Real tool outputs; source/versions in machine snapshot. Some sandbox-denied probes were repeated using normal approval.'},{action:'Generate public signature vector',command:['scripts/dev.ps1','exec','tsx','scripts/create-contract-vector.ts'],exit_code:0,outcome:'Only public key/signature persisted; private test key not exported.'},{action:'Recover generated dependencies',outcome:'PowerShell recursive move failed after partially preserving dependencies; atomic rename also failed despite shell exit 0. Neither was counted as success. Build-cache-disabled offline install and repeat succeeded.'},{action:'Git baseline synchronization',outcome:'Fetched origin; fast-forwarded Codex branch from 96b8bd7 to e5cdef3. No integration merge authored.'}],application_acceptance:'NOT_RUN; bootstrap subset and semantic unit tests only',limitations:['This index summarizes existing artifacts; it does not invent missing raw transcripts or promote task/test acceptance.']},null,2)+'\n');
const sourcePaths=[...new Set([...git(['diff','--name-only',base]).split(/\r?\n/),...git(['ls-files','--others','--exclude-standard']).split(/\r?\n/),`${directory}/A00-changed-files.json`])].filter(Boolean).sort();
const files=sourcePaths.map(path=>({path,sha256:path.endsWith('A00-changed-files.json')?null:existsSync(path)?createHash('sha256').update(readFileSync(path)).digest('hex'):null}));
writeFileSync(`${directory}/A00-changed-files.json`,JSON.stringify({task_id:'A00',base_commit:base,files,self_hash_note:'The list includes itself without a recursive digest; Git records its final bytes. Publication evidence is added in a separate follow-up commit.'},null,2)+'\n');
console.log(`Indexed ${commands.length} executed command records and ${files.length} changed files.`);
