import { createServer } from 'node:https';
import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { X509Certificate,createPrivateKey } from 'node:crypto';
import { runtimeConfig } from '../packages/auth/src/config.ts';
const config=runtimeConfig();if(config.profile!=='rehearsal')throw new Error('HTTPS candidate requires rehearsal profile');
const root=process.env.ORVIA_WORKSPACE_ROOT??process.cwd();
const cert=readFileSync(resolve(config.directory,'tls/server-cert.pem'));const key=readFileSync(resolve(config.directory,'tls/server-key.pem'));const ca=new X509Certificate(readFileSync(resolve(config.directory,'tls/ca-cert.pem')));const leaf=new X509Certificate(cert);
if(!ca.ca||leaf.ca||!leaf.verify(ca.publicKey)||!leaf.checkIP('127.0.0.1')||!leaf.checkPrivateKey(createPrivateKey(key))||Date.parse(leaf.validFrom)>Date.now()||Date.parse(leaf.validTo)<=Date.now())throw new Error('Invalid or expired local TLS identity');
const require=createRequire(resolve(root,'apps/web/package.json'));const next=require('next');
const app=next({dev:false,dir:resolve(root,'apps/web'),hostname:'127.0.0.1',port:config.app_port});
await app.prepare();
const server=createServer({key,cert,minVersion:'TLSv1.2'},app.getRequestHandler());
await new Promise<void>((done,fail)=>{server.once('error',fail);server.listen(config.app_port,'127.0.0.1',done);});
console.log(`Rehearsal HTTPS ready at ${config.origin}; local CA verification required.`);
let closing=false;
const stop=()=>{if(closing)return;closing=true;server.closeAllConnections();server.close(()=>{void app.close().then(()=>process.exit(0));});};
process.on('SIGINT',stop);process.on('SIGTERM',stop);process.on('message',message=>{if(message==='orvia-stop')stop();});
