import 'reflect-metadata';
import * as x509 from '@peculiar/x509';
import { randomBytes, X509Certificate, createPrivateKey } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadProfile } from '../packages/testing/src/config.ts';
import { writeEvidence } from '../packages/testing/src/evidence.ts';
import { privateDirectory } from './local-private.ts';
const p=loadProfile();
if(p.profile!=='rehearsal'||process.argv[2]!=='confirm:rehearsal')throw new Error('Named rehearsal TLS setup required');
const directory=resolve(p.directory,'tls');
if(existsSync(directory))throw new Error('TLS material already exists; no automatic replacement');
privateDirectory(directory);
const crypto=globalThis.crypto;
const algorithm={name:'ECDSA',namedCurve:'P-256',hash:'SHA-256'};
const caKeys=await crypto.subtle.generateKey(algorithm,true,['sign','verify']);
const leafKeys=await crypto.subtle.generateKey(algorithm,true,['sign','verify']);
const dates={notBefore:new Date(Date.now()-60000),notAfter:new Date(Date.now()+30*86400000)};
const serial=()=> '01'+randomBytes(15).toString('hex');
const name=`CN=ORVIA synthetic rehearsal ${p.installation_id}`;
const ca=await x509.X509CertificateGenerator.createSelfSigned({serialNumber:serial(),name,...dates,signingAlgorithm:algorithm,keys:caKeys,extensions:[new x509.BasicConstraintsExtension(true,0,true),new x509.KeyUsagesExtension(x509.KeyUsageFlags.keyCertSign|x509.KeyUsageFlags.cRLSign,true),await x509.SubjectKeyIdentifierExtension.create(caKeys.publicKey)]});
const leaf=await x509.X509CertificateGenerator.create({serialNumber:serial(),subject:'CN=localhost',issuer:name,...dates,signingAlgorithm:algorithm,publicKey:leafKeys.publicKey,signingKey:caKeys.privateKey,extensions:[new x509.BasicConstraintsExtension(false,undefined,true),new x509.KeyUsagesExtension(x509.KeyUsageFlags.digitalSignature,true),new x509.ExtendedKeyUsageExtension(['1.3.6.1.5.5.7.3.1']),new x509.SubjectAlternativeNameExtension([{type:'dns',value:'localhost'},{type:'ip',value:'127.0.0.1'}]),await x509.AuthorityKeyIdentifierExtension.create(caKeys.publicKey)]});
const parsedCa=new X509Certificate(ca.toString('pem'));const parsedLeaf=new X509Certificate(leaf.toString('pem'));
if(!parsedCa.ca||parsedLeaf.ca||!parsedLeaf.verify(parsedCa.publicKey)||!parsedLeaf.checkIP('127.0.0.1')||!parsedLeaf.checkHost('localhost'))throw new Error('Generated TLS chain validation failed');
const key=createPrivateKey({key:Buffer.from(await crypto.subtle.exportKey('pkcs8',leafKeys.privateKey)),format:'der',type:'pkcs8'}).export({type:'pkcs8',format:'pem'});
writeFileSync(resolve(directory,'server-key.pem'),key,{flag:'wx',mode:0o600});
writeFileSync(resolve(directory,'server-cert.pem'),leaf.toString('pem'),{flag:'wx',mode:0o600});
writeFileSync(resolve(directory,'ca-cert.pem'),ca.toString('pem'),{flag:'wx',mode:0o600});
// The one-use CA signing key is not persisted or exported.
writeEvidence('tls-material',{profile:p.profile,installation_id:p.installation_id,ca_fingerprint256:parsedCa.fingerprint256,leaf_fingerprint256:parsedLeaf.fingerprint256,not_after:parsedLeaf.validTo,tool:'@peculiar/x509 2.1.0 with native Node WebCrypto',openssl:process.versions.openssl,result:'GENERATED',limitations:['Local development CA; no OS/browser trust modification or production signing. Certificates expire after 30 days; replacement is an explicit operator task.']});
